In [1]:
college={
    "name":"Mangesh Kumar",
    "college_name":"GLA UNIVERSITY",
    "section":"CA",
    "grades":'A+',
    "city":"Mathura"
}
info={
    "name":"krish",
    "college_name":"GLA UNIVERSITY",
    "section":"CC",
    "grades":"A+",
    "city":"Mathura"
}
info2={
    "name":"Parth",
    "college_name":"GLA UNIVERSITY",
    "section":"CB",
    "grades":"A+",
    "city":"Mathura"
}

In [ ]:
marks = 72

if marks>=40:
  print("Pass")
else:
  print("Fail")

Pass

In [ ]:
marks=50
if(marks>=80):
  print("distinction")
elif(marks>=40 or marks<=79):
  print("pass")

pass

In [ ]:
marks=51
if(marks%2==0):
  print("even")
else:
  print("odd")

odd

In [ ]:
age=56
if(age<13):
  print("child")
elif(age>=13 and age<19):
  print("teenager")
else:
   print("old")

old

In [ ]:
# student=[{"name":"Aman","marks":90,"lab_assign":True,"city":"Agra","sec":"CB"},{"name":"Anubhav","marks":90,"lab_assign":True,"city":"Mathura","sec":"CB"},{"name":"Bhanu","marks":92,"lab_assign":True,"city":"Mathura","sec":"CB"},{"name":"Abhishek","marks":95,"lab_assign":True,"city":"Agra","sec":"CB"}]

students = [
    {"name": "Aman", "marks": 92, "attendance": 95, "lab_assignment": True},
    {"name": "Akshat", "marks": 75, "attendance": 85, "lab_assignment": True},
    {"name": "Anubhav", "marks": 58, "attendance": 60, "lab_assignment": True},
    {"name": "Abhishek", "marks": 88, "attendance": 90, "lab_assignment": False},
    {"name": "Bhanu", "marks": 35, "attendance": 80, "lab_assignment": True}
]

for student in students:
    if student["lab_assignment"] == False:
        result = "Lab Assignment Not Submitted"
    elif student["attendance"] < 75:
        result = "Low Attendance"
    elif student["marks"] >= 70:
        result = "Distinction"
    elif student["marks"] >= 40:
        result = "Pass"
    else:
        result = "Fail"

    print(student["name"], "-", result)

Aman - Distinction
Akshat - Distinction
Anubhav - Low Attendance
Abhishek - Lab Assignment Not Submitted
Bhanu - Fail

In [ ]:
marks=int(input("enter marks"))
def check(marks):
  if(marks>40):
    print("Pass")
  else:
    print("Fail")

SyntaxError: '(' was never closed (3854058988.py, line 1)

In [ ]:
import numpy as np
import pandas as pd
marks = np.array([78,91,55,72,40,88])
marks=marks.reshape(3,2)
print(marks.max())
# print(marks.max())

In [ ]:
df=pd.read_csv("/content/session4_dummy_students_data.csv.xls")

In [ ]:
df.head(

)

,student_id,name,age,city,math,science,english,attendance_percent,study_hours_per_week,assignments_submitted,final_project_score,avg,result
0,101,Aarav,16,Mumbai,78,84,69,92,8,9,82,77.000000,Pass
1,102,Diya,16,Delhi,91,88,94,96,11,10,93,91.000000,Pass
2,103,Kabir,17,Mathura,55,61,58,75,5,6,60,58.000000,Pass
3,104,Meera,16,Noida,72,79,81,89,7,8,78,77.333333,Pass
4,105,Rohan,17,Mumbai,40,52,47,68,3,5,45,46.333333,Pass

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             20 non-null     int64
 1   name                   20 non-null     object
 2   age                    20 non-null     int64
 3   city                   20 non-null     object
 4   math                   20 non-null     int64
 5   science                20 non-null     int64
 6   english                20 non-null     int64
 7   attendance_percent     20 non-null     int64
 8   study_hours_per_week   20 non-null     int64
 9   assignments_submitted  20 non-null     int64
 10  final_project_score    20 non-null     int64
 11  avg                    20 non-null     float64
 12  result                 20 non-null     object
dtypes: float64(1), int64(9), object(3)
memory usage: 2.2+ KB

In [ ]:
science_score=df["science"].to_numpy()
print(science_score)
print(type(science_score))
print(science_score.sum())

[84 88 61 79 52 93 70 92 57 76 63 81 45 86 54 90 69 85 49 73]
<class 'numpy.ndarray'>
1447

In [ ]:
science_score=df["science"].to_numpy()
math_score=df["math"].to_numpy()
english_score=df["english"].to_numpy()
avg=(math_score.sum()+science_score.sum()+english_score.sum())/3
print(avg )

1427.0

In [ ]:
science_score=df["science"].to_numpy()
math_score=df["math"].to_numpy()
english_score=df["english"].to_numpy()
df["avg"]=(science_score+math_score+english_score)/3
top_std=df[df["avg"]>80]
low_attd=df[df["attendance_percent"]<75]
mumbai_std=df[df["city"]=="mathura"]
top_std
low_attd
mumbai_std

Empty DataFrame
Columns: [student_id, name, age, city, math, science, english, attendance_percent, study_hours_per_week, assignments_submitted, final_project_score, avg, result]
Index: []

In [ ]:
# science_score=df["science"].to_numpy()
# math_score=df["math"].to_numpy()
# english_score=df["english"].to_numpy()
# df["avg"]=(science_score+math_score+english_score)/3
# if(df["attendance_percent"]>=40):
#   df["result"]="Pass"
# else:
#   df["result"]="Fail"
# result
import numpy as np

science_score = df["science"].to_numpy()
math_score = df["math"].to_numpy()
english_score = df["english"].to_numpy()

df["avg"] = (science_score + math_score + english_score) / 3
df["result"] = np.where(df["attendance_percent"] >= 40, "Pass", "Fail")
class_avg = df["avg"].mean()
print(class_avg)
avg_score=df["avg"].to_numpy()
print(avg_score.max())
print(avg_score.min())
#top student
print(df[df["avg"] ==avg_score.max()])
print(df[df["attendance_percent"]<75])
print(df[df["assignments_submitted"] < 6])
df.to_csv("session4_student_report.csv", index=False)

71.35000000000001
92.66666666666667
40.666666666666664
    student_id  name  age   city  math  science  english  attendance_percent  \
15         116  Riya   16  Noida    92       90       96                  98

    study_hours_per_week  assignments_submitted  final_project_score  \
15                    13                     10                   96

          avg result
15  92.666667   Pass
    student_id    name  age     city  math  science  english  \
4          105   Rohan   17   Mumbai    40       52       47
8          109  Vivaan   17   Mumbai    48       57       51
12         113     Dev   17   Mumbai    35       45       42
18         119    Yash   17  Mathura    43       49       46

    attendance_percent  study_hours_per_week  assignments_submitted  \
4                   68                     3                      5
8                   71                     4                      6
12                  62                     2                      4
18                  66                     3                      5

    final_project_score        avg result
4                    45  46.333333   Pass
8                    55  52.000000   Pass
12                   39  40.666667   Pass
18                   48  46.000000   Pass
    student_id   name  age     city  math  science  english  \
4          105  Rohan   17   Mumbai    40       52       47
12         113    Dev   17   Mumbai    35       45       42
18         119   Yash   17  Mathura    43       49       46

    attendance_percent  study_hours_per_week  assignments_submitted  \
4                   68                     3                      5
12                  62                     2                      4
18                  66                     3                      5

    final_project_score        avg result
4                    45  46.333333   Pass
12                   39  40.666667   Pass
18                   48  46.000000   Pass

In [ ]:
print(df[df["assignments_submitted"] < 6])

    student_id   name  age     city  math  science  english  \
4          105  Rohan   17   Mumbai    40       52       47
12         113    Dev   17   Mumbai    35       45       42
18         119   Yash   17  Mathura    43       49       46

    attendance_percent  study_hours_per_week  assignments_submitted  \
4                   68                     3                      5
12                  62                     2                      4
18                  66                     3                      5

    final_project_score        avg result
4                    45  46.333333   Pass
12                   39  40.666667   Pass
18                   48  46.000000   Pass